# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68b3405f42833a898ddec5fbf3b8214d25bcbf60024b39bb84017207a5758f9c2a1fc25cbdfb54e4730a57492d4c32c06bb2771d7495b861c15cae879f07d7c7

test:
  secret_key_base: d37e390b2fdc81e9ef0fa72521eaf963e3a9a31298b615084a7cd39a5ecf32b8a55d2e328a15a07cc0c72844bff4a94f7db3d94e6aa56c330d05a95e48e3a8ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
